"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["#validation-error[_ngcontent-%COMP%] {\r\n    text-align:center;\r\n    color:white;\r\n    background-color: $be-validation-error-color;\r\n}\r\n\r\nth[_ngcontent-%COMP%] {\r\n    font-size: 15px;\r\n}\r\ntd[_ngcontent-%COMP%] {\r\n    font-size: 12px;    \r\n}", "$be-validation-error-color[_ngcontent-%COMP%]:   #F0506E[_ngcontent-%COMP%];\r\n$be-app-theme-color[_ngcontent-%COMP%]:   rgb(15[_ngcontent-%COMP%], 122[_ngcontent-%COMP%], 229)[_ngcontent-%COMP%];"];
exports.styles = styles;
//# sourceMappingURL=presets-buyers.component.scss.shim.ngstyle.js.map