"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["header[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    font-size: 18px;\r\n    // height: 25px;\r\n    padding: 0px;\r\n}\r\n\r\n.uk-inline[_ngcontent-%COMP%] {\r\n    padding:10px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=header.component.scss.shim.ngstyle.js.map