"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["th[_ngcontent-%COMP%]{\r\n    font-size:12px;\r\n}\r\n\r\ntd[_ngcontent-%COMP%]{\r\n    font-size:10px;\r\n}\r\n\r\n.fab[_ngcontent-%COMP%] {\r\n    position : fixed;\r\n    z-index  : 5;\r\n    right    : 1.5%;\r\n    bottom   : 2%;\r\n    color: blue;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=orders.component.scss.shim.ngstyle.js.map