"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".icofont[_ngcontent-%COMP%] {\r\n    font-size: 15px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=order-po-grn.component.scss.shim.ngstyle.js.map