"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["#validation-error[_ngcontent-%COMP%] {\r\n    text-align:center;\r\n    color:white;\r\n    background-color: $be-validation-error-color;\r\n}\r\n\r\n//[_ngcontent-%COMP%]   th[_ngcontent-%COMP%] {\r\n//     font-size: 15px;\r\n// }\r\n//[_ngcontent-%COMP%]   td[_ngcontent-%COMP%] {\r\n//     font-size: 12px;    \r\n// }\r\ni[_ngcontent-%COMP%] {\r\n    font-size:18px;\r\n    padding: 0px 5px 0px 5px;\r\n}\r\n\r\nul.pagination[_ngcontent-%COMP%] {\r\n    display: inline\r\n}\r\nul.pagination[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]{\r\n    display: inline\r\n}\r\nul.pagination[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] {\r\n    font-size: 12px;\r\n}", "$be-validation-error-color[_ngcontent-%COMP%]:   #F0506E[_ngcontent-%COMP%];\r\n$be-app-theme-color[_ngcontent-%COMP%]:   rgb(15[_ngcontent-%COMP%], 122[_ngcontent-%COMP%], 229)[_ngcontent-%COMP%];"];
exports.styles = styles;
//# sourceMappingURL=presets-accessories.component.scss.shim.ngstyle.js.map